### ISSUE TITLE
The requested module '#minurl' does not provide an export named 'isUrl'

### ISSUE THREAD

**Issue by wmertens** [vfile/vfile#90] opened 2024-07-22 10:37 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/vfile/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/vfile/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/vfile/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Avfile&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

vfile 6.0.2

### Link to runnable example

https://github.com/QwikDev/qwik/actions/runs/10038434388/job/27740676939#step:10:478

### Steps to reproduce

After updating to 6.0.2 the e2e tests in Qwik started failing.

See https://github.com/QwikDev/qwik/actions/runs/10038434388/job/27740676939#step:10:478 (should be available for 30 days I think)

looks like something doesn't understand the import map?

### Expected behavior

it should just work :)

### Actual behavior

crashes

### Affected runtime and version

node 20

### Affected package manager and version

pnpm@9.0.5, vite@5.3.4

### Affected OS and version

linux

### Build and bundle tools

Vite

**Comment by wooorm** [comment] 2024-07-22 10:43
> looks like something doesn't understand the import map?

> it should just work :)

Right, sure, but that something is something in your tools right? Why raise it here and not there? 😅
Can you narrow it down?
It’s of interest that `isUrl` fails, not the other ones?

**Comment by wmertens** [comment] 2024-07-22 10:52
> Right, sure, but that something is something in your tools right? Why raise it here and not there? 😅

Hmm true :thinking:. Looks like it must be [`tsm`](https://github.com/lukeed/tsm), which we use with `playwright` for running the e2e tests.

So it's not really a bug on your side, but in any case 6.0.2 causes breakage when using common tools, and that would warrant a breaking release IMHO. With 6.0.1 the tests pass.

**Comment by wooorm** [comment] 2024-07-22 10:57
Do you know this one? https://xkcd.com/1172/

Looking at the tsm issue tracker, there seem to be a lot of bugs there, and it’s not maintained? I see very few commits too. Perhaps use something more stable?

**Comment by wmertens** [comment] 2024-07-22 10:58
indeed, looking at other options now. Still, seems possible that others will use tools with import map support issues.

**Comment by wooorm** [comment] 2024-07-22 11:09
Indeed!

Every release runs the risk of something accidentally breaking. Sometimes, some string occurs in a file, and suddenly typescript or some bundler fails. Or Safari crashes. Weird things happen!

I worried about this case earlier, that’s why we used an export map.
But I noticed that everything that supports export maps also supports import maps.
We have them in other places, likely already in your module graph. So I switched here too.

If the problem only happens in this rather experimental not very battle tested project `tsm` because it does not follow the spec, then I think it should be solved there.
If we indeed notice this happening in other tools, then I think it’s pragmatic to revert.

**Comment by rafaeldelboni** [comment] 2024-08-10 22:38
Just to add a comment, clojurescript most used tool (shadow-cljs) doesn't support this without fiddling with some noisy configurations, my build started having problems after a general version bump and vfile is a transient dependency, we will pint to 6.0.1 for now.

**Comment by wooorm** [comment] 2024-08-12 10:53
thanks for mentioning!

(aside: have you thought about a pr there?)

**Comment by CharltonSantana** [comment] 2024-09-18 08:11
Hey. Want to mention that I also have been getting this minpath issue with **6.0.2**. 
```
[vite]: Rollup failed to resolve import "#minpath" from "node_modules/vfile/lib/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "#minpath" from "node_modules/vfile/lib/index.js".
This is most likely unintended because it can break your application at runtime.
```
I don't currently have any availabiliy to look into the commits of the pacakge but I can confirm that downgrading the pacakge to **6.0.1** does fix this issue on build. If i find some time to look deeper into this I will.

Node v20.11.1
NPM v10.2.4
Vite v3.2.10

**Comment by wooorm** [comment] 2024-09-18 16:50
Rollup is known to work. Your configuration can likely be improved.

**Comment by wmertens** [comment] 2024-09-19 05:48
@CharltonSantana your Vite is super old

**Comment by CharltonSantana** [comment] 2024-09-23 08:17
@wooorm  Yeah you're right, if millions of people use something, there can't be any issues. Thank you.

@wmertens Good point!

**Comment by CharltonSantana** [comment] 2024-09-23 11:48
Thank you @wmertens. Updating our Vite pipelines fixed this.

**Comment by rafaeldelboni** [comment] 2024-10-17 18:51
Just an update from clojurescript side, since shadow-cljs version [2.28.18](https://github.com/thheller/shadow-cljs/commit/5c7d17afba2bf818cdf64ff21fb1f975b03ea4d5) this is supported natively and don't need extra configs.

**Comment by wooorm** [comment] 2024-10-18 09:22
Thanks for the update! Closing as it’s been a couple months

**Closed by wooorm** 2024-10-18 09:22 UTC
Labels: 🤞 phase/open
