### ISSUE TITLE
Native browser support?

### ISSUE THREAD

**Issue by 43081j** [vfile/vfile#71] opened 2022-01-04 22:47 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/vfile/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/vfile/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/vfile/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Avfile&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

N/A

### Steps to reproduce

Import vfile directly in a browser, using a CDN and an import map. Something like this:

```html
    <script type="importmap">
      {
        "imports": {
          "is-buffer": "https://unpkg.com/is-buffer",
          "https://unpkg.com/vfile@5.2.1/lib/minpath.js": "https://unpkg.com/vfile@5.2.1/lib/minpath.browser.js",
          "https://unpkg.com/vfile@5.2.1/lib/minproc.js": "https://unpkg.com/vfile@5.2.1/lib/minproc.browser.js",
          "https://unpkg.com/vfile@5.2.1/lib/minurl.js": "https://unpkg.com/vfile@5.2.1/lib/minurl.browser.js",
          "vfile": "https://unpkg.com/vfile@5.2.1/lib/index.js",
          "vfile-message": "https://unpkg.com/vfile-message@3.1.0/index.js",
          "unist-util-stringify-position": "https://unpkg.com/unist-util-stringify-position"
        }
      }
    </script>
```

Then some basic JS like this:

```ts
import {VFile} from 'vfile';

console.log(VFile);
```

### Expected behavior

No errors, VFile is logged to the console.

### Actual behavior

An error is thrown due to `is-buffer` having no default export.

`is-buffer` is a typical bit of NPM clutter, absolutely don't need to depend on it here. its near enough a one-liner package.

you could quite easily do the same check in your own, better maintained code, and it would work in a browser natively. you'd also get an extra win in that you have one less dependency.

**Comment by ChristianMurphy** [comment] 2022-01-05 02:21
An alternative worth noting, getting https://github.com/feross/is-buffer/pull/43 merged

**Comment by ChristianMurphy** [comment] 2022-01-05 03:50
Also https://cdn.skypack.dev/is-buffer could be used today

**Comment by wooorm** [comment] 2022-01-05 09:12
This is an external problem that can be solved by using a different CDN: skypack or esm.sh

**Closed by wooorm** 2022-01-05 09:12 UTC
Labels: 🤞 phase/open

**Comment by 43081j** [comment] 2022-01-05 09:44
@wooorm you are incorrect. those CDNs only work because they're running the sources through a bundler. your package _does not_ work in a browser natively. this should still be fixed on your end, you are depending on a nodejs dependency (which even specifies `engines: "node"` in its package manifest).

until you stop depending on node-only packages, this package does not work in browsers.

**Comment by wooorm** [comment] 2022-01-05 10:33
> you are incorrect

What is incorrect?

> this should still be fixed on your end

No.

> you are depending on a nodejs dependency

It is not a nodejs dependency.

> which even specifies `engines: "node"` in its package manifest, of which, a browser is not one

That is not what the `engines` field means.

> until you stop depending on node-only packages, this package does not work in browsers.

Removing `is-buffer` does not make it work.

> as its also just clutter we can quite easily drop

There is no clutter.

**Comment by 43081j** [comment] 2022-01-05 10:58
It most definitely is a nodejs dependency, the package manifest specifies that the _required_ engine is node, not a browser.

it also depends on commonjs, a nodejs-specific module system.

`engines` exists to specify which engines and versions of them your code works on.

removing `is-buffer` _does_ make it work, it is the only node-only dependency in your dependency tree. it is clutter, its a one liner, something you could have in your code instead.

im not trying to be argumentative here, this package literally does not work in browsers. you do depend on a node-only package. of course, it would work if we bundled it (which is the only reason it works via skypack and similar), but that doesn't change the fact your package does not work natively in a browser. this should be fixed.

**Comment by 43081j** [comment] 2022-01-05 11:21
there is a way around it, by shipping code which runs in a browser natively: ESM. many of us have already started to push in this direction and a huge amount of packages have already migrated to it.

some still ship both via package exports, but at least support native platforms still.

i am aware that being able to check if the value is a buffer is important,  but you don't need a dependency for that (adding install time, bundle size, dependency tree depth, etc). you can just do the same check yourself in your own code, its a very small amount of code (`obj.constructor && typeof obj.constructor.isBuffer === 'function' && obj.constructor.isBuffer(obj)`).

You have moved to ESM, but you import a package which relies on commonjs. thus, this cannot work natively in a browser.

its such a small, simple change to make it work natively, then it really will be native ESM.

**Comment by wooorm** [comment] 2022-01-05 15:49
> huge amount of packages have already migrated to it.

It‘s pretty small in comparison: https://twitter.com/wooorm/status/1459058036409090065.

> but at least support native platforms still.

What are “native platforms”?

> but you don't need a dependency for that 

This project and all of unified has been around for a while. `is-buffer` has changed over that time. Copy/pasting packages into other packages (aka, creating “bundles”) is not a solution.
I am not interesting in removing dependencies because they are CJS.

> thus, this cannot work natively in a browser.

Correct.

> its such a small, simple change to make it work natively, then it really will be native ESM.

You are conflating things. This package is ESM. Import maps are not standardized yet, they’re not “ESM”. Bare imports do not work in browsers.

You can solve this yourself: Either link to skypack/esmsh or map `is-buffer` to your own copy/pasted ESM file.

> you also need to strip your dependency tree of non-esm dependencies so the full tree works natively, as-is.

It is not a solution for every maintainer to ship bundles and never use dependencies.

**Comment by 43081j** [comment] 2022-01-05 17:51
It is small in comparison, which is why people like you and i should be pushing that number higher.

This package is ESM, yes, but it depends on CJS code, which means it will not work in a browser (since it depends on node-specific interop/modules).

It isn't the consumer's problem to solve. This is currently a node-only package and I am requesting that you allow us to make it also work in browsers. I'm really not sure why you would be against that, it has no downsides, you'd be helping out other projects a lot by doing it and you'd be improving your package.

> It is not a solution for every maintainer to ship bundles and never use dependencies.

nobody said it was. if for some reason you like having tiny dependencies, you could alternatively find an ESM one that does the same job or improve the existing one to be shipped as ESM. it doesn't matter to anyone here whether you do it that way or by removing the dependency, and neither of those solutions is anything to do with "bundles".

**Comment by ChristianMurphy** [comment] 2022-01-05 17:59
@43081j browsers are supported, as noted in https://github.com/vfile/vfile/issues/71#issuecomment-1005359734
Skypack CDN could be used, either as a whole, or used with import map to target just the single dependency.

If you prefer to have native ESM in the dependencies themselves https://github.com/vfile/vfile/issues/71#issuecomment-1005325731 notes two PRs: feross/is-buffer#43 or feross/is-buffer#44 merged which you could advocate for.

**Comment by 43081j** [comment] 2022-01-05 18:38
@ChristianMurphy _bundlers_ are supported, this package does not natively work in a browser, @wooorm agreed with that above.

until this package has no commonjs dependencies, it does not work in a browser as-is.

it would be a great improvement if it did. it seems the two options to achieve that are:
* Remove the CJS dependencies (is-buffer)
* Update the CJS dependencies to support ESM

both are ways to achieve the same thing: removing CJS dependencies.

**Comment by wooorm** [comment] 2022-01-05 21:31
You seem to ignore the many responses you got. This seems malicious.

It is not going to change. You can solve this in many ways on your end. Or you can get the external package to update.

**Comment by 43081j** [comment] 2022-01-05 22:17
I'm sorry you see it that way, it is in no way malicious and would be a mistake to interpret it as such. 

This library does not support browsers. Due to that, projects depending on it also do not support browsers. That is a real shame, so I came here to request that you add support for browsers. The only way you can achieve that is by shipping esm (all the way down the dependency tree) or by shipping a bundle which itself is esm. 

I'm really at a loss as to why you would actively avoid supporting browsers. The benefit is so great, we would be able to use things like milkdown (editor which depends on this) directly in a browser without the need for bundling/transformation. 

Various people from the web components community have read this issue for me as I wanted to check if I'm missing something. All were as baffled as me. Supporting browsers should be fundamental to projects like this and the ones which depend on it. 

The fact that the one thing blocking it from working in a browser is a redundant one-liner package only adds to the bafflement. 

I'm sorry if this somehow seemed malicious to you, it never was and it is sad to see browser support shot down so freely.

**Comment by ChristianMurphy** [comment] 2022-01-05 23:25
A few things are off.

First, it is confusing and frustrating to see issues opened every stop along the way of your tech stack, except the actual package which is commonjs, and causing the perceived issue https://github.com/feross/is-buffer.

Second, the premise of the issue patently ignore how import maps work, they can point to anything.

* The raw unpkg version of `is-buffer`, which will break, but you can do it.
* The transformed version provided by skypack, which works swimmingly as demonstrated earlier.
* It can be pointed to a different module entirely.
* Even a local file could be used, hand coded with ESM to your hearts delight.

vfile does not force that choice, it is :100: your choice what it points to.

Which leaves it unclear why vfile, should be changed.
It is neither the root cause nor a blocker to the fix.

You seem to have more interest in sharing a diatribe, than articulating a clear issue or using any of the multitude of viable options offered.

**Comment by 43081j** [comment] 2022-01-06 01:30
Yes, a consumer can transform this module's dependencies using tooling to make it work in a browser. This is what bundlers and skypack are doing, transforming commonjs to esm. 

But that tooling being available doesn't change the fact that this package doesn't work in a browser as-is. 

So my request was simple: can this package change to work in browsers?

To achieve that, is-buffer needs moving to ESM or dropping. Either way, eventually this package then has to change (whether it's a dependency upgrade or removal). 

It is a lot simpler than this issue has been bloated into. Whether you fix it or the dependency fixes it, it is a thing to be fixed. Native browser support does not currently exist and would be nice to have, I am requesting it.

**Comment by wooorm** [comment] 2022-01-06 09:18
Your original issue is lacking much information. It’s an XY issue focussing on one symptom.
It is problematic because if `vfile` would change, other packages also use `is-buffer`, and other CJS packages are used throughout the collective as well.
It is also problematic because import maps are not part of the existing web platform, nor is manually creating import maps from npm packages scalable.

Your original issue can be solved in several ways, including 2 ways by you (a different CDN and you mapping `is-buffer` to your own manual file), one way in the external package, and by us.
The tradeoff is not worth it: it is not scalable across unified or all of npm to bundle packages before publishing. While it might help you in this case, it would dramatically increase bundle size, decrease performance, and result in bugs, for everyone (including you).
There are enough, good, alternatives.

There is nothing “native” about your reproduction and proposed solution: CDN.js and manually creating an import map are not native ESM. What you suggest as “solution” doesn’t make it so.

---

> I am requesting it.

Here’s how this project works: you get this code for free, that’s it. Nothing more. Issues and discussions are not part of what you get. You’re wasting time debating random internet strangers that don’t owe you anything. The answer is no, because the tradeoff is not worth it.
You don’t get to make requests. You get to ask for help per the [support docs](https://github.com/vfile/.github/blob/main/support.md#asking-quality-questions) and you get to help per the [contribute docs](https://github.com/vfile/.github/blob/main/contributing.md).

I will block you if you do not respect our community guidelines..

---

I’m locking this issue.
