### ISSUE TITLE
Broken on webpack 6

### ISSUE THREAD

**Issue by prcdpr** [vfile/vfile#58] opened 2020-12-01 21:15 UTC
`@elastic/eui` is dependent on `vfile` which is dependent on `replace-ext`.

`replace-ext` just recently got broken on webpack 6 and following error message shows:

```
 ERROR  Failed to compile with 2 errors                                                                                                                                                                      22:05:59
 error  in ./node_modules/replace-ext/index.js

Module not found: Error: Can't resolve 'path' in '\node_modules\replace-ext'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

 error  in ./node_modules/vfile/core.js

Module not found: Error: Can't resolve 'path' in '\node_modules\vfile'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
```

Please drop the dependency on `replace-ext`, replacing filename extension can be easily polyfilled without external dependency as this is relatively easy to implement.

**Comment by ChristianMurphy** [comment] 2020-12-01 21:21
duplicate of https://github.com/vfile/vfile/discussions/57 please see the resolution there

**Closed by ChristianMurphy** 2020-12-01 21:21 UTC
Labels: 🐛 type/bug, 🔍 status/open

**Comment by ChristianMurphy** [comment] 2020-12-01 21:27
Also there is no webpack 6 yet, you mean webpack 5. :slightly_smiling_face:

**Comment by ChristianMurphy** [comment] 2020-12-01 22:02
@prcdpr I also added some additional context at https://github.com/vfile/vfile/discussions/57#discussioncomment-144288
